#org: UmairButt
app: appstore-google-reviews
service: appstore-google-reviews
#frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs16.x
plugins:
  - serverless-offline

functions:
  api:
    handler: handler.handler
    environment: ${file(env.${opt:stage, self:provider.stage}.json)}
    events:
      - http:
          path: /authorizeGoogleBusiness
          method: GET
          cors:
            origin: "*" # <-- Specify allowed origin
            headers: "*"

      - http:
          path: /callBack
          method: GET
          cors:
            origin: "*" # <-- Specify allowed origin
            headers: "*"

      - http:
          path: /failed
          method: GET
          cors:
            origin: "*" # <-- Specify allowed origin
            headers: "*"

      - http:
          path: /success
          method: GET
          cors:
            origin: "*" # <-- Specify allowed origin
            headers: "*"
